using System.Collections.Generic;

namespace BossChecklist;

/// <summary>
/// 界面文字。数据来自 tModLoader 版 BossChecklist 的语言文件（英文），
/// 键名去掉 "Mods.BossChecklist." 前缀，其余和原模组一一对应。
/// 这个文件是脚本生成的，改文字请改这里（别去改原模组的 hjson）。
/// </summary>
internal static class LocalizationData
{
    public static readonly Dictionary<string, string> Strings = new Dictionary<string, string>
    {
        { "BossSpawnInfo.BloodMoon", "Occurs randomly at the start of night or can be summoned with a [i:4271] which can be dropped by any blood moon enemy. Can start when any player in the world has more than 100 health and the current moon phase is NOT a new moon. Lasts until sunrise." },
        { "BossSpawnInfo.BrainofCthulhu", "Use [i:1331] or break 3 Crimson Hearts in a crimson chasm." },
        { "BossSpawnInfo.CultistBoss", "Kill the 4 cultists outside the dungeon after defeating Golem." },
        { "BossSpawnInfo.DD2Betsy", "Spawns on Wave 7, the final wave, of Old One's Army (Tier 3)." },
        { "BossSpawnInfo.DD2DarkMageT3", "Appears in wave 5 (Tier 1) and waves 5 & 6 (Tier 3) during the Old One's Army event! Start Old One's Army with [i:3816] and [i:3828]" },
        { "BossSpawnInfo.DD2OgreT3", "Appears in wave 7 (Tier 2) and waves 4 & 6 (Tier 3) during the Old One's Army event! Start Old One's Army with [i:3816] and [i:3828]" },
        { "BossSpawnInfo.Deerclops", "Use [i:5120] in a Snow biome. Spawns naturally at midnight during a Blizzard." },
        { "BossSpawnInfo.DukeFishron", "Fish in ocean using the [i:2673] as bait, which can be caught in an underground Glowing Mushroom biome during hardmode." },
        { "BossSpawnInfo.EaterofWorlds", "Use [i:70] or break 3 Shadow Orbs in a corruption chasm." },
        { "BossSpawnInfo.Eclipse", "Has a 1/20 chance to occur each day upon dawn, as soon as any Mechanical Boss has been defeated. Alternatively, summon with a [i:2767]. Lasts until nightfall." },
        { "BossSpawnInfo.Everscream", "Spawns during Wave 4 of Frost Moon. Start Frost Moon with [i:1958]" },
        { "BossSpawnInfo.EyeofCthulhu", "Use [i:43] at night, or 1/3 chance nightly if over 200 HP." },
        { "BossSpawnInfo.FrostLegion", "Use a [i:602], which can be found by opening [i:1869], during the Christmas season. Lasts until enough enemies are defeated." },
        { "BossSpawnInfo.FrostMoon", "Summoned with a [i:1958] at night. Lasts until sunrise." },
        { "BossSpawnInfo.GoblinArmy", "Has a 1 in 3 chance of occurring every dawn if at least one Shadow Orb/Crimson Heart has been destroyed, at least one player has 200 health or more, and there is not a Goblin Army already in progress. It can also be summoned manually using a [i:361]. Lasts until enough enemies are defeated." },
        { "BossSpawnInfo.Golem", "Use [i:1293] on Lihzahrd Altar, found deep in the Jungle Temple." },
        { "BossSpawnInfo.HallowBoss", "Kill [i:4961] in the Hallow biome, which can be found on the Hallow surface between 7:30pm and 12:00am after Plantera has been defeated." },
        { "BossSpawnInfo.IceQueen", "Spawns during Wave 11 of Frost Moon. Start Frost Moon with [i:1958]" },
        { "BossSpawnInfo.KingSlime", "Use [i:560], randomly in outer 3rds of map, or kill 150 slimes during slime rain." },
        { "BossSpawnInfo.LunarEvent", "Defeat the Lunatic Cultist found outside the dungeon. Each pillar spawns in its own area within the world. Lasts until all 4 pillars are destroyed." },
        { "BossSpawnInfo.MartianMadness", "After defeating Golem, find a Martian Probe above ground and allow it to find you and escape. Lasts until enough enemies are defeated." },
        { "BossSpawnInfo.MartianSaucer", "Occasionally appears during Martian Madness! Start Martian Madness by being detected by an alien probe." },
        { "BossSpawnInfo.MoonLord", "Use [i:3601] or defeat all 4 pillars." },
        { "BossSpawnInfo.MoonLord_Tremor", "Use [i:3601] or defeat all 5 pillars. [c/FF0000:Starts Tremode!]" },
        { "BossSpawnInfo.MourningWood", "Spawns during Wave 4 of Pumpkin Moon. Start Pumpkin Moon with [i:1844]" },
        { "BossSpawnInfo.OldOnesArmy", "After finding the Tavernkeep, purchase and activate [i:3816] with [i:3828]. Lasts until all waves are cleared." },
        { "BossSpawnInfo.PirateInvasion", "Occurs randomly once at least one altar has been destroyed. Can be summoned with a [i:1315], which can be obtained from killing any enemy in the Ocean biome during Hardmode. Lasts until enough enemies are defeated." },
        { "BossSpawnInfo.PirateShip", "Occasionally appears during a Pirate Invasion! Start Pirate Invasion with [i:1315]" },
        { "BossSpawnInfo.Plantera", "Break a Plantera's Bulb in jungle after 3 Mechanical bosses have been defeated." },
        { "BossSpawnInfo.PumpkinMoon", "Summoned with a [i:1844] at night. Lasts until sunrise." },
        { "BossSpawnInfo.Pumpking", "Spawns during Wave 7 of Pumpkin Moon. Start Pumpkin Moon with [i:1844]" },
        { "BossSpawnInfo.QueenBee", "Use [i:1133] or break a Bee Hive's Larva found in the jungle." },
        { "BossSpawnInfo.QueenSlimeBoss", "Use [i:4988] in the Hallow biome, which can be found in the Underground Hallow among Crystal Shards growing on Pearlstone and Pink Ice blocks." },
        { "BossSpawnInfo.SantaNK1", "Spawns during Wave 7 of Frost Moon. Start Frost Moon with [i:1958]" },
        { "BossSpawnInfo.Skeletron", "Visit the dungeon and talk to the old man at night or kill the Clothier with [i:1307] at night." },
        { "BossSpawnInfo.SkeletronPrime", "10% chance to randomly spawn each night after the first altar is destroyed, until one mech boss is defeated. Use [i:557] at night to spawn." },
        { "BossSpawnInfo.TheDestroyer", "10% chance to randomly spawn each night after the first altar is destroyed, until one mech boss is defeated. Use [i:556] at night to spawn." },
        { "BossSpawnInfo.TheTwins", "10% chance to randomly spawn each night after the first altar is destroyed, until one mech boss is defeated. Alternatively, Use [i:544] at night to spawn." },
        { "BossSpawnInfo.TorchGod", "Place 101 torches while underground. The event starts once the last torch is placed." },
        { "BossSpawnInfo.Unknown", "Spawn conditions unknown" },
        { "BossSpawnInfo.WallofFlesh", "Spawn by throwing [i:267] or the Guide into lava in the Underworld. [c/FF0000:Starts Hardmode!]" },
        { "ChatMessages.Defeated.Generic", "{0} is down!" },
        { "ChatMessages.Defeated.GenericMoonLordHead", "Moon Lord's Head is down!" },
        { "ChatMessages.Defeated.GenericSkeletronHand", "Skeletron's Hand is down!" },
        { "ChatMessages.Defeated.GolemFistLeft", "{0} is destroyed!" },
        { "ChatMessages.Defeated.GolemFistRight", "{0} is destroyed!" },
        { "ChatMessages.Defeated.GolemHead", "The {0} has detached from the body!" },
        { "ChatMessages.Defeated.LunarTowerNebula", "The {0} has fallen!" },
        { "ChatMessages.Defeated.LunarTowerSolar", "The {0} has fallen!" },
        { "ChatMessages.Defeated.LunarTowerStardust", "The {0} has fallen!" },
        { "ChatMessages.Defeated.LunarTowerVortex", "The {0} has fallen!" },
        { "ChatMessages.Defeated.MoonLordHand", "A True Eye of Cthulhu exits the {0}!" },
        { "ChatMessages.Defeated.MoonLordHead", "A True Eye of Cthulhu exits the head of the {0}!" },
        { "ChatMessages.Defeated.PrimeCannon", "The {0} has exploded!" },
        { "ChatMessages.Defeated.PrimeLaser", "The {0} has overheated!" },
        { "ChatMessages.Defeated.PrimeSaw", "The {0} has malfunctioned!" },
        { "ChatMessages.Defeated.PrimeVice", "The {0} has collapsed!" },
        { "ChatMessages.Defeated.Retinazer", "{0} has been defeated!" },
        { "ChatMessages.Defeated.SkeletronHand", "A {0} hand has fractured!" },
        { "ChatMessages.Defeated.Spazmatism", "{0} has been defeated!" },
        { "ChatMessages.Despawn.Day", "{0} flees as the sun rises..." },
        { "ChatMessages.Despawn.Generic", "{0} is no longer after you..." },
        { "ChatMessages.EventEnd.BloodMoon", "The Blood Moon falls past the horizon..." },
        { "ChatMessages.EventEnd.Eclipse", "The solar eclipse has ended... until next time..." },
        { "ChatMessages.EventEnd.FrostMoon", "The Frost Moon melts as the sun rises..." },
        { "ChatMessages.EventEnd.Generic", "The {0} has ended..." },
        { "ChatMessages.EventEnd.PumpkinMoon", "The Pumpkin Moon ends its harvest..." },
        { "ChatMessages.Loss.BrainofCthulhu", "{0} vanishes into the pits of the crimson..." },
        { "ChatMessages.Loss.CultistBoss", "{0} goes back to its devoted worship..." },
        { "ChatMessages.Loss.DukeFishron", "{0} returns to the ocean depths..." },
        { "ChatMessages.Loss.EaterofWorlds", "{0} burrows back underground..." },
        { "ChatMessages.Loss.EyeofCthulhu", "{0} has disappeared into the night sky..." },
        { "ChatMessages.Loss.Generic", "{0} has killed every player!" },
        { "ChatMessages.Loss.Golem", "{0} deactivates in the bowels of the temple..." },
        { "ChatMessages.Loss.HallowBoss", "{0} dissipates to hallow light..." },
        { "ChatMessages.Loss.KingSlime", "{0} leaves in triumph..." },
        { "ChatMessages.Loss.MoonLord", "{0} has left this realm..." },
        { "ChatMessages.Loss.Plantera", "{0} continues its rest within the jungle..." },
        { "ChatMessages.Loss.QueenBee", "{0} returns to her colony's nest..." },
        { "ChatMessages.Loss.QueenSlimeBoss", "{0} pompously bounces away..." },
        { "ChatMessages.Loss.Skeletron", "{0} continues to torture the Old Man..." },
        { "ChatMessages.Loss.SkeletronPrime", "{0} begins searching for a new victim..." },
        { "ChatMessages.Loss.TheDestroyer", "{0} seeks for another world to devour..." },
        { "ChatMessages.Loss.TheTwins", "{0} continues its observations..." },
        { "ChatMessages.Loss.WallofFlesh", "{0} has managed to cross the underworld..." },
        { "Checklist.CelestialPillars", "Celestial Pillars" },
        { "Checklist.ToggleCompletedTooltip", "Toggle Completed" },
        { "Checklist.ToggleEventsTooltip", "Toggle Events" },
        { "Checklist.ToggleMiniBossesTooltip", "Toggle Mini Bosses" },
        { "Checklist.ToggleShowHiddenBossesTooltip", "Toggle Show Hidden Bosses\n(Alt-Click to clear Hidden bosses)\n(Alt-Click on boss to hide)" },
        { "Configs.BossLogConfiguration.AutomaticChecklist.Label", "Automatic Checklist" },
        { "Configs.BossLogConfiguration.AutomaticChecklist.Tooltip", "Entries will be marked automatically when defeated. Disabling requires the user to manually check off entries.\nWhether enabled or disabled, you can manually mark entries using right-click on their name." },
        { "Configs.BossLogConfiguration.BossLogColor.Label", "Boss Log Color" },
        { "Configs.BossLogConfiguration.BossLogColor.Tooltip", "Choose the color of your Boss Log!" },
        { "Configs.BossLogConfiguration.BossLogPos.Label", "Open Log Button Position" },
        { "Configs.BossLogConfiguration.BossLogPos.Tooltip", "Alternatively, hold right-click while hovering over the Boss Log button to move it wherever you'd like with ease!\nPosition is measured from bottom right corner of screen." },
        { "Configs.BossLogConfiguration.CheckDroppedLoot.Label", "Only check droppable loot" },
        { "Configs.BossLogConfiguration.CheckDroppedLoot.Tooltip", "Items that are not dropped by the entry, such as music boxes, will not be counted towards the loot check." },
        { "Configs.BossLogConfiguration.ColoredBossText.Label", "Colored Boss Text" },
        { "Configs.BossLogConfiguration.ColoredBossText.Tooltip", "The boss text in the table of contents will be green when defeated and red when not.\nIf next check is enabled, the next boss will be yellow." },
        { "Configs.BossLogConfiguration.Debug.Label", "[i:3625] [c/ffeb6e:Debug Tools for Mod Developers] [i:3619]" },
        { "Configs.BossLogConfiguration.Debug.Tooltip", "" },
        { "Configs.BossLogConfiguration.DisableProgressionMode.Label", "Disable Progression Mode" },
        { "Configs.BossLogConfiguration.DisableProgressionMode.Tooltip", "" },
        { "Configs.BossLogConfiguration.DisplayName", "Boss Log Customization" },
        { "Configs.BossLogConfiguration.DrawNextMark.Label", "Next Boss Check" },
        { "Configs.BossLogConfiguration.DrawNextMark.Tooltip", "Puts a circle in the checkbox to indicate it is the next undefeated boss to fight." },
        { "Configs.BossLogConfiguration.EnableProgressionMode.Label", "Enable Progression Mode" },
        { "Configs.BossLogConfiguration.EnableProgressionMode.Tooltip", "" },
        { "Configs.BossLogConfiguration.FilterBosses.Label", "Filter bosses in list" },
        { "Configs.BossLogConfiguration.FilterBosses.Tooltip", "" },
        { "Configs.BossLogConfiguration.FilterEvents.Label", "Filter events in list" },
        { "Configs.BossLogConfiguration.FilterEvents.Tooltip", "" },
        { "Configs.BossLogConfiguration.FilterMiniBosses.Label", "Filter mini bosses in list" },
        { "Configs.BossLogConfiguration.FilterMiniBosses.Tooltip", "" },
        { "Configs.BossLogConfiguration.Headers.BlindMode", "[i:888] [c/ffeb6e:Progression Mode - Defeat bosses to unlock their entry!]" },
        { "Configs.BossLogConfiguration.Headers.BossLogChecklist", "[i:903] [c/ffeb6e:Boss Log Checklist]" },
        { "Configs.BossLogConfiguration.Headers.BossLogUI", "[i:149] [c/ffeb6e:Boss Log UI]" },
        { "Configs.BossLogConfiguration.HideUnavailable.Label", "Hide unavailable bosses" },
        { "Configs.BossLogConfiguration.HideUnavailable.Tooltip", "If enabled, unavailable bosses will be removed from the Boss Log's table of contents.\nEx. Frost Legion while it is not Xmas." },
        { "Configs.BossLogConfiguration.HideUnsupported.Label", "Hide unsupported bosses" },
        { "Configs.BossLogConfiguration.HideUnsupported.Tooltip", "If enabled, bosses that have not fully integrated will be removed from the Boss Log's table of contents." },
        { "Configs.BossLogConfiguration.LootChecklist.Label", "Enable loot/collectible checklist" },
        { "Configs.BossLogConfiguration.LootChecklist.Tooltip", "The table of contents will also check if you've obtained all of a boss's loot and collectible items." },
        { "Configs.BossLogConfiguration.MaskBossLoot.Label", "Hide boss drops until entry is defeated" },
        { "Configs.BossLogConfiguration.MaskBossLoot.Tooltip", "" },
        { "Configs.BossLogConfiguration.MaskHardMode.Label", "Hide hardmode content until in hardmode" },
        { "Configs.BossLogConfiguration.MaskHardMode.Tooltip", "Hides ALL content, overriding the options you have toggled above." },
        { "Configs.BossLogConfiguration.MaskNames.Label", "Hide names until entry is defeated" },
        { "Configs.BossLogConfiguration.MaskNames.Tooltip", "" },
        { "Configs.BossLogConfiguration.MaskTextures.Label", "Hide textures until entry is defeated" },
        { "Configs.BossLogConfiguration.MaskTextures.Tooltip", "" },
        { "Configs.BossLogConfiguration.OnlyBosses.Label", "Boss Log only shows boss content" },
        { "Configs.BossLogConfiguration.OnlyBosses.Tooltip", "If enabled, the checklist and page navigation will only give access boss entries.\nNote: Filter configs below will be ignored when enabled." },
        { "Configs.BossLogConfiguration.ProgressionPrompt.Label", "Disable Progressive Checklist prompt" },
        { "Configs.BossLogConfiguration.ProgressionPrompt.Tooltip", "While enabled, this will prevent the prompt from appearing for newly-created characters." },
        { "Configs.BossLogConfiguration.ProgressiveChecklist.Label", "Progressive Checklist" },
        { "Configs.BossLogConfiguration.ProgressiveChecklist.Tooltip", "Hides content until the entry is encountered or beaten." },
        { "Configs.BossLogConfiguration.SelectedCheckmarkType.Label", "Checklist Marking Type" },
        { "Configs.BossLogConfiguration.SelectedCheckmarkType.Tooltip", "" },
        { "Configs.BossLogConfiguration.ShowInteractionTooltips.Label", "Enable Interactions Tab" },
        { "Configs.BossLogConfiguration.ShowInteractionTooltips.Tooltip", "When enabled, a small tab can be hovered over for an explanation on how to use the alternative interactions of the current page.\nAlternative interactions examples include right-clicking on a Table of Contents entry to manually mark it as defeated." },
        { "Configs.BossLogConfiguration.ShowProgressBars.Label", "Show Progress Bars" },
        { "Configs.BossLogConfiguration.ShowProgressBars.Tooltip", "When disabled, the total progress bars at the bottom of the table of contents will not show." },
        { "Configs.BossLogConfiguration.SpawnItemCraftingChecklist.Label", "Enable spawn item crafting checklist" },
        { "Configs.BossLogConfiguration.SpawnItemCraftingChecklist.Tooltip", "When enabled, crafting recipes for spawn info items will function as a checklist.\nIngredients will be checked off if the correct amount of items are in the inventory.\nCrafting stations will be checked off if the player is nearby the correct tiles." },
        { "Configs.BossLogConfiguration.UnmaskNextCheck.Label", "Show the name of the next entry to fight" },
        { "Configs.BossLogConfiguration.UnmaskNextCheck.Tooltip", "Note that the Next Boss Check AND Hide Boss Names must be enabled for this to work." },
        { "Configs.CheckType.Check_Empty.Label", "✓  [ ]" },
        { "Configs.CheckType.Check_Empty.Tooltip", "" },
        { "Configs.CheckType.Check_X.Label", "✓  X" },
        { "Configs.CheckType.Check_X.Tooltip", "" },
        { "Configs.CheckType.StrikeThrough.Label", "Strike-through" },
        { "Configs.CheckType.StrikeThrough.Tooltip", "" },
        { "Configs.CheckType.Tooltip", "" },
        { "Configs.CheckType.X_Empty.Label", "X  [ ]" },
        { "Configs.CheckType.X_Empty.Tooltip", "" },
        { "Configs.Common.HostChange", "Only the host is allowed to change this config." },
        { "Configs.Common.InvalidChange", "You cannot change the '{0}' config while {1} is active!" },
        { "Configs.DebugTools.AccessInternalNames.Label", "Access Entry Keys" },
        { "Configs.DebugTools.AccessInternalNames.Tooltip", "Adds a button on each entry page that displays and copies the Entry Key to the in-game clipboard.\nUseful for mod developers making cross-mod content." },
        { "Configs.DebugTools.DisableAutoLocalization.Label", "Disable Auto Localization" },
        { "Configs.DebugTools.DisableAutoLocalization.Tooltip", "BossChecklist will detect old calls and create localizations for LocalizedText submissions needed for the new calls.\nThe new calls do not require these localizations but will default to them if null is passed.\nSet to true to prevent new localizations from being created by BossChecklist." },
        { "Configs.DebugTools.EnabledResetOptions.Label", "Enable Reset Data Options" },
        { "Configs.DebugTools.EnabledResetOptions.Tooltip", "When enabled, your are able to clear or reset certain data within the Boss Log.\nIncludes: Clearing hidden entries, clearing marked entries, clearing loot checklist, and resetting records.\n[c/FF0000:The 'Enable Interactions Tab' config is required in order to use this config.]" },
        { "Configs.DebugTools.InactiveBossCheck.Label", "Inactive Boss Check" },
        { "Configs.DebugTools.InactiveBossCheck.Tooltip", "While enabled, a message will be displayed in chat when records have begun calculating, if record tracking is enabled.\nThis should also display a message in chat when a despawn message appears, if despawn messages are enabled.\nThese messages should appear when a boss has been defeated or a boss has despawned, respectively." },
        { "Configs.DebugTools.ModCallLogVerbose.Label", "Mod.Call Log Verbose" },
        { "Configs.DebugTools.ModCallLogVerbose.Tooltip", "If true, logs will display more information on entry data creation within tModLoader logs.\nInvalid or incorrect usage of mod calls are displayed regardless of setting." },
        { "Configs.DebugTools.ShowCollectionType.Label", "Show Auto-detected Collectible Type" },
        { "Configs.DebugTools.ShowCollectionType.Tooltip", "Boss collectible itemslots will be labeled with the assigned collectible type." },
        { "Configs.DebugTools.ShowProgressionValue.Label", "Access Progression Values" },
        { "Configs.DebugTools.ShowProgressionValue.Tooltip", "Shows the progression value when hovering over an entry within the table of contents and when viewing an entry's page.\nThe progression value is what determines how entries are ordered in the checklist." },
        { "Configs.DebugTools.Tooltip", "" },
        { "Configs.FeatureConfiguration.AllowNewRecords.Label", "Allow New Records" },
        { "Configs.FeatureConfiguration.AllowNewRecords.Tooltip", "When disabled, only your previous attempt is recorded.\nFirst victory and personal best records will not be overwritten." },
        { "Configs.FeatureConfiguration.DespawnMessageType.Label", "Boss Despawn Annoucements" },
        { "Configs.FeatureConfiguration.DespawnMessageType.Tooltip", "Despawn messages will appear in chat when a boss becomes inactive.\nIf enabled, choose between generic or unique messages." },
        { "Configs.FeatureConfiguration.DisplayName", "Other features" },
        { "Configs.FeatureConfiguration.DisplayRecordTracking.Label", "Display Record Tracker Values" },
        { "Configs.FeatureConfiguration.DisplayRecordTracking.Tooltip", "When enabled, record tracking values are shown and updated during a boss fight.\nNote: Strictly for singleplayer, currently. Does not work in multiplayer." },
        { "Configs.FeatureConfiguration.EnableBossRadar.Label", "Enable Boss Radar" },
        { "Configs.FeatureConfiguration.EnableBossRadar.Tooltip", "" },
        { "Configs.FeatureConfiguration.FragmentsOnMap.Label", "Fragments display on the map" },
        { "Configs.FeatureConfiguration.FragmentsOnMap.Tooltip", "" },
        { "Configs.FeatureConfiguration.Headers.BossRadar", "[i:3084] [c/ffeb6e:Boss Radar]" },
        { "Configs.FeatureConfiguration.Headers.BossRecords", "[i:3095] [c/ffeb6e:Boss Records]" },
        { "Configs.FeatureConfiguration.Headers.ChatMessages", "[i:3037] [c/ffeb6e:Chat Messages]" },
        { "Configs.FeatureConfiguration.Headers.ItemMapDetection", "[i:893] [c/ffeb6e:Item Map Detection]" },
        { "Configs.FeatureConfiguration.LimbMessages.Label", "Non-Boss Defeated Annoucements" },
        { "Configs.FeatureConfiguration.LimbMessages.Tooltip", "Messages will appear in chat when an important component of an entry is defeated.\nExamples include: Skeletron's Hands, Retinazor/Spazmatism, the Celestial Pillars, etc." },
        { "Configs.FeatureConfiguration.MoonMessages.Label", "Moon Event Ending Annoucements" },
        { "Configs.FeatureConfiguration.MoonMessages.Tooltip", "Messages will appear in chat when a vanilla moon event has ended.\nMoon events include: Blood Moon, Eclipse, Pumpkin Moon and Frost Moon." },
        { "Configs.FeatureConfiguration.NewRecordLogGlow.Label", "Enable New Record Log Glow" },
        { "Configs.FeatureConfiguration.NewRecordLogGlow.Tooltip", "When enabled, setting a new record will put a rainbow glow on the following:\n- Boss Log button\n- Table of Contents entry name" },
        { "Configs.FeatureConfiguration.RadarBlacklist.Label", "Radar Blacklist" },
        { "Configs.FeatureConfiguration.RadarBlacklist.Tooltip", "The selected NPCs will not be tracked by the radar." },
        { "Configs.FeatureConfiguration.RadarMiniBosses.Label", "Whitelist mini bosses" },
        { "Configs.FeatureConfiguration.RadarMiniBosses.Tooltip", "Note: This only works properly with mini bosses that have head icons." },
        { "Configs.FeatureConfiguration.RadarOpacity.Label", "Radar Opacity" },
        { "Configs.FeatureConfiguration.RadarOpacity.Tooltip", "Adjust how transparent the radar's icon will be." },
        { "Configs.FeatureConfiguration.RecordTrackingEnabled.Label", "Enable Boss Record Tracking" },
        { "Configs.FeatureConfiguration.RecordTrackingEnabled.Tooltip", "When enabled, fight stats will be tracked for records." },
        { "Configs.FeatureConfiguration.ScalesOnMap.Label", "Shadow Scales and Tissue Samples display on the map" },
        { "Configs.FeatureConfiguration.ScalesOnMap.Tooltip", "" },
        { "Configs.FeatureConfiguration.TimeValueFormat.Label", "Time Value Format" },
        { "Configs.FeatureConfiguration.TimeValueFormat.Tooltip", "Standard: [0:00:00.000]\nSimple: [0h 0m 0s 0ms]" },
        { "Configs.FeatureConfiguration.TimerSounds.Label", "Respawn Timer Sounds" },
        { "Configs.FeatureConfiguration.TimerSounds.Tooltip", "If enabled, the last 3 seconds of your respawn time will have sound indicators." },
        { "Configs.FeatureConfiguration.TreasureBagsOnMap.Label", "Treasure bags display on the map" },
        { "Configs.FeatureConfiguration.TreasureBagsOnMap.Tooltip", "" },
        { "Configs.FilterType.Hide.Label", "Hide" },
        { "Configs.FilterType.Hide.Tooltip", "" },
        { "Configs.FilterType.HideWhenCompleted.Label", "Hide When Completed" },
        { "Configs.FilterType.HideWhenCompleted.Tooltip", "" },
        { "Configs.FilterType.Show.Label", "Show" },
        { "Configs.FilterType.Show.Tooltip", "" },
        { "Configs.FilterType.Tooltip", "" },
        { "Configs.MessageType.Disabled.Label", "Disabled" },
        { "Configs.MessageType.Disabled.Tooltip", "" },
        { "Configs.MessageType.Generic.Label", "Generic" },
        { "Configs.MessageType.Generic.Tooltip", "" },
        { "Configs.MessageType.Tooltip", "" },
        { "Configs.MessageType.Unique.Label", "Unique" },
        { "Configs.MessageType.Unique.Tooltip", "" },
        { "Configs.TimeFormat.Simple.Label", "Simple" },
        { "Configs.TimeFormat.Simple.Tooltip", "" },
        { "Configs.TimeFormat.Standard.Label", "Standard" },
        { "Configs.TimeFormat.Standard.Tooltip", "" },
        { "Configs.TimeFormat.Tooltip", "" },
        { "Keybinds.ToggleChecklist.DisplayName", "Toggle Boss Checklist" },
        { "Keybinds.ToggleLog.DisplayName", "Toggle Boss Log" },
        { "Log.Common.Boss", "Boss" },
        { "Log.Common.BossLog", "Boss Log" },
        { "Log.Common.BossPlural", "Bosses" },
        { "Log.Common.Disabled", "disabled" },
        { "Log.Common.Enabled", "enabled" },
        { "Log.Common.Entry", "Entry" },
        { "Log.Common.Event", "Event" },
        { "Log.Common.EventPlural", "Events" },
        { "Log.Common.MiniBoss", "Mini-boss" },
        { "Log.Common.MiniBossPlural", "Mini-bosses" },
        { "Log.Common.PartiallyEnabled", "partially enabled" },
        { "Log.Credits.Devs", "Contributors" },
        { "Log.Credits.Learn", "View the mod description to learn how." },
        { "Log.Credits.Mods", "Registered Mods" },
        { "Log.Credits.ModsEmpty", "None of your loaded mods are registered!" },
        { "Log.Credits.NoIcon", "Mod icon not found!" },
        { "Log.Credits.Notice", "[List only contains loaded mods]" },
        { "Log.Credits.Register", "Register your own mod!" },
        { "Log.Credits.Titles.CoOwner", "Co-Owner & Maintainer" },
        { "Log.Credits.Titles.Contributor", "Code Contributor" },
        { "Log.Credits.Titles.EarlyTesting", "Early Testing" },
        { "Log.Credits.Titles.Owner", "Creator & Owner" },
        { "Log.Credits.Titles.Sprites", "Boss Log Sprites" },
        { "Log.EntryPage.CopyKey", "Click to copy the internal 'entry key' to clipboard\n{0}" },
        { "Log.EntryPage.Defeated", "Defeated in {0}{1}" },
        { "Log.EntryPage.LogFeaturesNotAvailable", "Records, spawn items, and the loot table are disabled for this page. The mod has either not submitted enough info for a page or has it improperly set up." },
        { "Log.EntryPage.NotImplemented", "The display for this page is unavailable. The mod has either not submitted a page or has it improperly set up." },
        { "Log.EntryPage.Undefeated", "Undefeated in {0}" },
        { "Log.EntryPage.ViewPage", "Click to view page" },
        { "Log.HintTexts.ClearAllRecords", "Hold ALT and right-click this button to reset the list record values" },
        { "Log.HintTexts.ClearHidden", "Hold ALT and right-click this button to clear all hidden entries" },
        { "Log.HintTexts.ClearItems", "Hold ALT and right-click this button to mark the listed items as unobtained" },
        { "Log.HintTexts.ClearMarked", "Hold ALT and right-click this button to clear all marked entries" },
        { "Log.HintTexts.ClearRecord", "Hold ALT and right-click the icon of a record to reset its value" },
        { "Log.HintTexts.HideEntry", "Left-click an entry to hide it from the checklist" },
        { "Log.HintTexts.MarkEntry", "Right-click an entry to mark it as defeated" },
        { "Log.HintTexts.RemoveItem", "Hold ALT and right-click an item to mark it as unobtained" },
        { "Log.Indicator.AutomaticChecklist", "The checklist will automatically check off entries" },
        { "Log.Indicator.ManualChecklist", "Entries must be manually checked off by the user" },
        { "Log.Indicator.OnlyBossContentDisabled", "All content is available to be displayed" },
        { "Log.Indicator.OnlyBossContentEnabled", "Only boss content is available to be displayed" },
        { "Log.Indicator.ProgressionMode", "Progression mode is {0}" },
        { "Log.LootAndCollection.ItemIsExpertOnly", "This item is only obtainable in Expert Mode" },
        { "Log.LootAndCollection.ItemIsLocked", "This item has special requirements to unlock" },
        { "Log.LootAndCollection.ItemIsMasterOnly", "This item is only obtainable in Master Mode" },
        { "Log.LootAndCollection.MaskedItems", "Defeat this entry to view its loot and collectibles" },
        { "Log.LootAndCollection.Obtained", "This item has been obtained!" },
        { "Log.LootAndCollection.Researched", "This item has been researched!" },
        { "Log.ProgressionMode.AskEnable", "Do you want to enable the Progression Checklist?" },
        { "Log.ProgressionMode.BeforeYouBegin", "Before you begin..." },
        { "Log.ProgressionMode.Description", "The Progressive Checklist will limit and hide entry content until the entry is defeated or marked as completed. If you are looking to do a blind play-through then you might want to consider enabling this feature. The Boss Log is disabled until you make a selection or reopen it with the prompt configuration disabled" },
        { "Log.ProgressionMode.DisablePrompt", "Don't show this prompt again" },
        { "Log.ProgressionMode.IsEnabled", "[i:888] The Progressive Checklist is fully or partially enabled!\nThis will mask some information about bosses until they have been defeated.\nTo disable or configure the progressive checklist go to:\nSettings > Mod Configurations > Boss Checklist: Boss Log Customization\nand scroll down to the Progress Mode configs" },
        { "Log.ProgressionMode.SelectAnOption", "Please select an option below..." },
        { "Log.ProgressionMode.SelectConfig", "Close Boss Log and configure the progressive checklist..." },
        { "Log.ProgressionMode.SelectDisable", "Continue with the progressive checklist disabled...\n* All page info content is unlocked from the start\n* Nothing hidden. No limits." },
        { "Log.ProgressionMode.SelectEnable", "Continue with the progressive checklist fully enabled...\n* Page info content is locked for undefeated entries\n* Portraits and names are masked\n* Boss loot locked until entry defeation\n* Next check enabled, reducing info limitations (recommended)" },
        { "Log.Records.Category.Cycle", "Cycle record categories" },
        { "Log.Records.Category.FirstVictory", "First Victory" },
        { "Log.Records.Category.PersonalBest", "Personal Best" },
        { "Log.Records.Category.PreviousAttempt", "Previous Attempt" },
        { "Log.Records.Category.WorldRecord", "World Records" },
        { "Log.Records.ClaimRecord", "Be the first to claim the world record!" },
        { "Log.Records.Hit", "{0} {^0:hit;hits}" },
        { "Log.Records.Hours", "{0}h {1}m {2}s ({3}ms)" },
        { "Log.Records.KDR", "{0} kills / {1} deaths" },
        { "Log.Records.Minutes", "{0}m {1}s ({2}ms)" },
        { "Log.Records.NewRecord", "New Personal Best!" },
        { "Log.Records.NewWorldRecord", "New World Record!" },
        { "Log.Records.NoHit", "No hit!" },
        { "Log.Records.NoRecord", "No record" },
        { "Log.Records.PreviousBest", "Your Previous Best" },
        { "Log.Records.RecordHolder", "Record Holder(s)" },
        { "Log.Records.Seconds", "{0} secon{^0:d;ds} ({1}ms)" },
        { "Log.Records.Title.Duration", "Fight Duration" },
        { "Log.Records.Title.DurationWorld", "Quickest Fight" },
        { "Log.Records.Title.FirstVictory", "Play Time" },
        { "Log.Records.Title.HitsTaken", "Hits Received" },
        { "Log.Records.Title.HitsTakenWorld", "Lowest Hits Taken" },
        { "Log.Records.Title.PersonalBest", "Kill Death Ratio" },
        { "Log.Records.Title.PreviousAttempt", "Attempt" },
        { "Log.Records.Title.WorldRecord", "Global KDR" },
        { "Log.Records.Tooltip.Duration", "The quickest time this boss was defeated!" },
        { "Log.Records.Tooltip.FirstVictory", "Total play time your character has been active, up until the first boss kill!" },
        { "Log.Records.Tooltip.HitsTaken", "Avoid as many attacks as you can! Try to defeat this boss untouched!" },
        { "Log.Records.Tooltip.PersonalBest", "Total times you killed this boss and total times this boss has killed you!" },
        { "Log.Records.Tooltip.PreviousAttempt", "Total times you have encountered this boss!" },
        { "Log.Records.Tooltip.WorldRecord", "Global kills and deaths from all players for this boss!" },
        { "Log.Records.TotalKills", "Total kills" },
        { "Log.Records.Unchallenged", "Unchallenged" },
        { "Log.SpawnInfo.ByHand", "By Hand" },
        { "Log.SpawnInfo.CycleRecipe", "Cycle alternative recipes" },
        { "Log.SpawnInfo.NoInfo", "No info available" },
        { "Log.SpawnInfo.NoSpawnItem", "This {0} has no spawn item" },
        { "Log.SpawnInfo.Noncraftable", "This item is not craftable" },
        { "Log.SpawnInfo.RecipeFrom", "Recipe from: {0}" },
        { "Log.TableOfContents.AllCollectibles", "All boss collectibles obtained!" },
        { "Log.TableOfContents.AllDropLoot", "All non-collectible boss loot obtained!" },
        { "Log.TableOfContents.AllLoot", "All boss loot obtained!" },
        { "Log.TableOfContents.Filter.Disabled", "Filter disabled due to 'Only Show Boss Content' config" },
        { "Log.TableOfContents.Filter.Hide", "{0}: Hidden" },
        { "Log.TableOfContents.Filter.HideWhenCompleted", "{0}: Hidden when defeated" },
        { "Log.TableOfContents.Filter.Show", "{0}: Shown" },
        { "Log.TableOfContents.Filter.ToggleHiddenClose", "Confirm & close hidden list" },
        { "Log.TableOfContents.Filter.ToggleHiddenOpen", "Open hidden list" },
        { "Log.TableOfContents.Hardmode", "Hardmode" },
        { "Log.TableOfContents.PreHardmode", "Pre-Hardmode" },
        { "Log.TableOfContents.ProgressBarListMods", "Click to switch to Mod List mode" },
        { "Log.TableOfContents.ProgressBarListTypes", "Click to switch to Entry Type mode" },
        { "Log.Tabs.Credits", "Credits" },
        { "Log.Tabs.LootAndCollectibles", "Loot & Collectibles" },
        { "Log.Tabs.NextEntry", "Next {0}:\n{1}" },
        { "Log.Tabs.Records", "Records" },
        { "Log.Tabs.SpawnInfo", "Spawn Info" },
        { "Log.Tabs.TableOfContents", "Table of Contents" },
        { "Log.Tabs.ToggleFilters", "Toggle Filters" },
        { "LogMessage.BelongsToInvasion", "{0} has attempted to edit the npc pool of '{1}'. This entry is an event that is supported by tModLoader's 'NPCID.Sets.BelongsToInvasion' sets. SubmitEventNPCs will still be supported, but it is recommended to use the sets instead, where given. Using these sets for ModNPCs will automatically add them to an entry's NPC pool without additional mod calls." },
        { "LogMessage.DownedIsNull", "Submitted parameter determined to be null when creating a Boss Log Entry for [{0}]. Entry will not be added until ModCall is resolved." },
        { "LogMessage.DuplicateEntry", "Check your code for duplicate entries or typos, as this entry has already been registered: [{0} {1}]" },
        { "LogMessage.InvalidEventEntry", "{0} is not an event entry and cannot take calls from {1}" },
        { "LogMessage.InvalidOrphanKey", "A '{0}' call from {1} contains an invalid key ({2}) and will be ignored." },
        { "LogMessage.LastUpdated_ModCall", "The Boss Log Mod Call has been last updated on BossChecklist ({0}). Check out the GitHub Wiki guide to stay updated on the latest changes!" },
        { "LogMessage.LastUpdated_Progression", "Progression values for vanilla entries have been last updated on BossChecklist ({0})" },
        { "LogMessage.LateCall", "Call Warning: The attempted message, '{0}', was sent too early. Expect the Call message to return incomplete data. For best results, call in PostAddRecipes." },
        { "LogMessage.ModCallDocumentation", "Updated Mod.Call documentation for BossChecklist can be found here: https:" },
        { "LogMessage.MustContainMod", "Invalid mod instance passed ({0}). Your call must contain a Mod instance to generate an entry key." },
        { "LogMessage.MustContainMod_Orphan", "Invalid mod instance passed ({0}). Your call must contain a Mod instance for logging purposes." },
        { "LogMessage.MustContainName", "Invalid internal name passed ({internalName}). Your call must contain a string comprised of letters and/or digits without whitespace characters in order to generate an entry key." },
        { "LogMessage.NoLogging", "Boss Log integration messages will not be logged." },
        { "LogMessage.OldCall", "The '{0}' call is an old call and is now obsolete. Use '{1}' instead. {2} entries include: [{3}]" },
        { "LogMessage.OldCall_Orphan", "{0} mod call from {1} is structured improperly. Mod developers can refer to link below:\nhttps:" },
        { "LogMessage.RegisteredBosses", "{0} has successfully registered {1} bosses: {2}" },
        { "LogMessage.RegisteredEvents", "{0} has successfully registered {1} events: {2}" },
        { "LogMessage.RegisteredMiniBosses", "{0} has successfully registered {1} mini-bosses: {2}" },
        { "LogMessage.SuccessfulOrphanData", "{0} has successfully registered {1} '{2}' orphan data value(s)" },
    };

    /// <summary>条目显示名的特例。没列在这里的条目会自动取第一个 NPC 的原版名字。</summary>
    public static readonly Dictionary<string, string> EntryNames = new Dictionary<string, string>
    {
        { "KingSlime", "King Slime" },
        { "EyeofCthulhu", "Eye of Cthulhu" },
        { "EaterofWorlds", "Eater of Worlds" },
        { "BrainofCthulhu", "Brain of Cthulhu" },
        { "QueenBee", "Queen Bee" },
        { "Skeletron", "Skeletron" },
        { "Deerclops", "Deerclops" },
        { "WallofFlesh", "Wall of Flesh" },
        { "QueenSlimeBoss", "Queen Slime" },
        { "TheTwins", "The Twins" },
        { "TheDestroyer", "The Destroyer" },
        { "SkeletronPrime", "Skeletron Prime" },
        { "Plantera", "Plantera" },
        { "Golem", "Golem" },
        { "DD2Betsy", "Betsy" },
        { "HallowBoss", "Empress of Light" },
        { "DukeFishron", "Duke Fishron" },
        { "CultistBoss", "Lunatic Cultist" },
        { "MoonLord", "Moon Lord" },
        { "TorchGod", "Torch God" },
        { "BloodMoon", "Blood Moon" },
        { "GoblinArmy", "Goblin Army" },
        { "OldOnesArmy", "Old One's Army" },
        { "DarkMage", "Dark Mage" },
        { "Ogre", "Ogre" },
        { "FrostLegion", "Frost Legion" },
        { "PirateInvasion", "Pirate Invasion" },
        { "PirateShip", "Flying Dutchman" },
        { "Eclipse", "Solar Eclipse" },
        { "PumpkinMoon", "Pumpkin Moon" },
        { "MourningWood", "Mourning Wood" },
        { "Pumpking", "Pumpking" },
        { "FrostMoon", "Frost Moon" },
        { "Everscream", "Everscream" },
        { "SantaNK1", "Santa-NK1" },
        { "IceQueen", "Ice Queen" },
        { "MartianMadness", "Martian Madness" },
        { "MartianSaucer", "Martian Saucer" },
        { "LunarEvent", "Celestial Pillars" },
    };
}
