using System.Collections.Generic;

namespace BossChecklist;

/// <summary>
/// 界面文字。数据来自 tModLoader 版 BossChecklist 的语言文件（中文，缺的条目回落到英文），
/// 键名去掉 "Mods.BossChecklist." 前缀，其余和原模组一一对应。
/// 这个文件是脚本生成的，改文字请改这里（别去改原模组的 hjson）。
/// </summary>
internal static class LocalizationData
{
    public static readonly Dictionary<string, string> Strings = new Dictionary<string, string>
    {
        { "BossSpawnInfo.BloodMoon", "至少一个玩家的生命值超过 120, 且当前月相不是新月时在每天黄昏随机发生. 持续到日出. 或者使用掉落自血月期间敌人的 [i:4271] 在夜晚召唤." },
        { "BossSpawnInfo.BrainofCthulhu", "在猩红之地使用 [i:1331] 或在猩红之地的掌形洞穴中破坏 3 个猩红之心." },
        { "BossSpawnInfo.CultistBoss", "杀死在击败石巨人后出现在地牢门前的 4 个信徒." },
        { "BossSpawnInfo.DD2Betsy", "在旧日军团入侵事件 T3 的第 7 波生成." },
        { "BossSpawnInfo.DD2DarkMageT3", "出现在T1第5波、T3第5,6波的旧日军团事件! 通过使用 [i:3816] 和 [i:3828] 来开启事件." },
        { "BossSpawnInfo.DD2OgreT3", "出现在T2第7波、T3第4,6波的旧日军团事件! 通过使用 [i:3816] 和 [i:3828] 来开启事件." },
        { "BossSpawnInfo.Deerclops", "在雪原使用 [i:5120] 召唤. 其会自然生成在暴雪期间的午夜." },
        { "BossSpawnInfo.DukeFishron", "使用 [i:2673] 作为鱼饵在海边钓出, 在困难模式下, 松露虫可以在地下发光蘑菇地找到." },
        { "BossSpawnInfo.EaterofWorlds", "在腐化之地使用 [i:70] 或在腐化之地的裂缝中破坏 3 个暗影珠." },
        { "BossSpawnInfo.Eclipse", "一旦打败任意机械 Boss, 则在每天黎明都有 1/20 几率发生. 或者, 用 [i:2767] 召唤. 持续到夜幕降临." },
        { "BossSpawnInfo.Everscream", "在寒霜之月第4波及其之后生成. 通过使用 [i:1958] 以开始寒霜之月." },
        { "BossSpawnInfo.EyeofCthulhu", "在夜晚使用 [i:43], 当至少一名玩家最大生命值大于等于 200, 防御值大于等于 10 且未曾被击败时在每个夜晚有 1/3 的几率生成." },
        { "BossSpawnInfo.FrostLegion", "在困难模式(肉山后), 使用在圣诞节期间敌怪掉落的 [i:1869] 开出的 [i:602] 即可召唤. 此事件在打败了一定数量的雪人后就会完成." },
        { "BossSpawnInfo.FrostMoon", "在夜晚用 [i:1958] 召唤. 在黎明时结束." },
        { "BossSpawnInfo.GoblinArmy", "如果有至少一个暗影珠/猩红之心已被摧毁, 且至少有一名玩家有 200 或更多生命值, 并且没有正在进行中的 哥布林军队, 那么哥布林军队这个事件每逢黎明就有 1/3 几率发生. 它也可以用 [i:361] 来手动召唤. 此事件在打败了一定数量的哥布林后就会完成." },
        { "BossSpawnInfo.Golem", "在神庙祭坛中使用 [i:1293] , 祭坛可在丛林神庙的最深处发现." },
        { "BossSpawnInfo.HallowBoss", "在神圣之地击杀 [i:4961] . 在世纪之花被击败后的晚上7:30到12:00之间, [i:4961] 可以在神圣之地的地表找到." },
        { "BossSpawnInfo.IceQueen", "在寒霜之月第11波及其之后生成. 通过使用 [i:1958] 以开始寒霜之月." },
        { "BossSpawnInfo.KingSlime", "使用 [i:560], 或在地图外侧的两个 1/6 （最左边或最右边）范围内随机生成, 或者在史莱姆雨期间杀死 150 个史莱姆." },
        { "BossSpawnInfo.LunarEvent", "通过打败地牢外的拜月教邪教徒来开启. 每个柱子均匀分布在世界各处." },
        { "BossSpawnInfo.MartianMadness", "在击败石巨人后, 找到火星探测器并让它探测到玩家后不被摧毁地离开屏幕以召唤. 此事件在打败了一定数量的火星后就会完成." },
        { "BossSpawnInfo.MartianSaucer", "偶尔地出现在火星暴乱事件! 通过被火星探测器探测以开始火星暴乱." },
        { "BossSpawnInfo.MoonLord", "困难模式中, 在击杀石巨人后使用 [i:3601] 或摧毁所有 4 个天界塔以召唤." },
        { "BossSpawnInfo.MoonLord_Tremor", "使用 [i:3601] 或摧毁所有 5 个天界塔以召唤. [c/FF0000:击杀此Boss将开启震颤模式!]" },
        { "BossSpawnInfo.MourningWood", "在南瓜月第4波及其之后生成. 通过使用 [i:1844] 以开始南瓜月." },
        { "BossSpawnInfo.OldOnesArmy", "找到酒保之后, 用 [i:3828] 购买并激活 [i:3816] 即可召唤. 持续至所有进攻波结束或水晶被砍破后." },
        { "BossSpawnInfo.PirateInvasion", "它可以在困难模式随机生成, 或通过使用 [i:1315] 来召唤,  [i:1315] 可以通过在困难模式期间击杀海洋生物群落中的任意敌怪来获得. 此事件在打败了一定数量的海盗后就会完成." },
        { "BossSpawnInfo.PirateShip", "偶尔地出现在海盗入侵事件! 通过使用 [i:1315] 以开始海盗入侵." },
        { "BossSpawnInfo.Plantera", "在 3 个机械Boss全部被击败后, 在地下丛林找到并破坏世纪之花球茎以召唤." },
        { "BossSpawnInfo.PumpkinMoon", "在夜晚用 [i:1844] 召唤. 在黎明时结束." },
        { "BossSpawnInfo.Pumpking", "在南瓜月第7波及其之后生成. 通过使用 [i:1844] 以开始南瓜月." },
        { "BossSpawnInfo.QueenBee", "在丛林中使用 [i:1133] 或破坏地下丛林中蜂巢中的幼虫." },
        { "BossSpawnInfo.QueenSlimeBoss", "在神圣之地使用 [i:4988] 召唤, [i:4988] 可以在珍珠石块或粉冰雪块上找到." },
        { "BossSpawnInfo.SantaNK1", "在寒霜之月第7波及其之后生成. 通过使用 [i:1958] 以开始寒霜之月." },
        { "BossSpawnInfo.Skeletron", "在夜晚造访地牢并与老人谈话或通过戴上 [i:1307] 在夜晚杀死裁缝." },
        { "BossSpawnInfo.SkeletronPrime", "还未击败过至少一次时, 在已敲碎至少一个祭坛的前提下每个黄昏有 10% 的几率生成. 或在夜晚使用 [i:557] 以召唤." },
        { "BossSpawnInfo.TheDestroyer", "还未击败过至少一次时, 在已敲碎至少一个祭坛的前提下每个黄昏有 10% 的几率生成. 或在夜晚使用 [i:556] 以召唤." },
        { "BossSpawnInfo.TheTwins", "还未击败过至少一次时, 在已敲碎至少一个祭坛的前提下每个黄昏有 10% 的几率生成. 或在夜晚使用 [i:544] 以召唤." },
        { "BossSpawnInfo.TorchGod", "通过在地底放置101支火把来召唤. 事件开始于第101支火把被放置后." },
        { "BossSpawnInfo.Unknown", "生成条件未知" },
        { "BossSpawnInfo.WallofFlesh", "通过将 [i:267] 或向导本人投入地狱中炙热的岩浆来召唤. [c/FF0000:击杀此Boss将开启困难模式!]" },
        { "ChatMessages.Defeated.Generic", "{0}已被击倒!" },
        { "ChatMessages.Defeated.GenericMoonLordHead", "月亮领主的手已被击倒!" },
        { "ChatMessages.Defeated.GenericSkeletronHand", "骷髅王之手已被击倒!" },
        { "ChatMessages.Defeated.GolemFistLeft", "{0}被摧毁了!" },
        { "ChatMessages.Defeated.GolemFistRight", "{0}被摧毁了!" },
        { "ChatMessages.Defeated.GolemHead", "{0}已脱离身体!" },
        { "ChatMessages.Defeated.LunarTowerNebula", "{0}已倒塌!" },
        { "ChatMessages.Defeated.LunarTowerSolar", "{0}已倒塌!" },
        { "ChatMessages.Defeated.LunarTowerStardust", "{0}已倒塌!" },
        { "ChatMessages.Defeated.LunarTowerVortex", "{0}已倒塌!" },
        { "ChatMessages.Defeated.MoonLordHand", "一颗克苏鲁真眼已脱离了{0}!" },
        { "ChatMessages.Defeated.MoonLordHead", "一颗克苏鲁真眼已脱离了{0}的头部!" },
        { "ChatMessages.Defeated.PrimeCannon", "{0}爆炸了!" },
        { "ChatMessages.Defeated.PrimeLaser", "The {0}过热了!" },
        { "ChatMessages.Defeated.PrimeSaw", "{0}发生故障了!" },
        { "ChatMessages.Defeated.PrimeVice", "{0}坍塌了!" },
        { "ChatMessages.Defeated.Retinazer", "{0}已被击败!" },
        { "ChatMessages.Defeated.SkeletronHand", "{0}的一个手断裂了!" },
        { "ChatMessages.Defeated.Spazmatism", "{0}已被击败!" },
        { "ChatMessages.Despawn.Day", "{0}在黎明时逃跑了..." },
        { "ChatMessages.Despawn.Generic", "{0}失去了对你的兴趣..." },
        { "ChatMessages.EventEnd.BloodMoon", "赤色之月落至地平线之下..." },
        { "ChatMessages.EventEnd.Eclipse", "日食暂时停止了..." },
        { "ChatMessages.EventEnd.FrostMoon", "寒霜之月在日光中融化了..." },
        { "ChatMessages.EventEnd.Generic", "{0}结束了..." },
        { "ChatMessages.EventEnd.PumpkinMoon", "南瓜月下的狂欢结束了..." },
        { "ChatMessages.Loss.BrainofCthulhu", "{0}消失于赤色深渊..." },
        { "ChatMessages.Loss.CultistBoss", "{0}虔诚地崇拜着..." },
        { "ChatMessages.Loss.DukeFishron", "{0}潜入深海..." },
        { "ChatMessages.Loss.EaterofWorlds", "{0}钻回了地下..." },
        { "ChatMessages.Loss.EyeofCthulhu", "{0}隐没在暮色中..." },
        { "ChatMessages.Loss.Generic", "{0}杀死了所有玩家!" },
        { "ChatMessages.Loss.Golem", "{0}停止运作..." },
        { "ChatMessages.Loss.HallowBoss", "{0}在神圣辉光中消散..." },
        { "ChatMessages.Loss.KingSlime", "{0}班师回朝..." },
        { "ChatMessages.Loss.MoonLord", "{0}从世间离去..." },
        { "ChatMessages.Loss.Plantera", "{0}休眠于地下丛林..." },
        { "ChatMessages.Loss.QueenBee", "{0}在蜂群中回巢..." },
        { "ChatMessages.Loss.QueenSlimeBoss", "{0}傲慢的跳走了..." },
        { "ChatMessages.Loss.Skeletron", "{0}的诅咒仍禁锢着老人..." },
        { "ChatMessages.Loss.SkeletronPrime", "{0}开始寻找新的受害者..." },
        { "ChatMessages.Loss.TheDestroyer", "{0}寻找着新的世界以吞噬之..." },
        { "ChatMessages.Loss.TheTwins", "{0}持续观察着一切..." },
        { "ChatMessages.Loss.WallofFlesh", "{0}穿过了整个地狱..." },
        { "Checklist.CelestialPillars", "天界柱" },
        { "Checklist.ToggleCompletedTooltip", "开关显示已完成的" },
        { "Checklist.ToggleEventsTooltip", "开关显示事件" },
        { "Checklist.ToggleMiniBossesTooltip", "开关显示小Boss" },
        { "Checklist.ToggleShowHiddenBossesTooltip", "开关显示隐藏的Boss\n(Alt-点击以清除被隐藏的Boss)\n(Alt-点击Boss以将其隐藏)" },
        { "Configs.BossLogConfiguration.AutomaticChecklist.Label", "自动日志" },
        { "Configs.BossLogConfiguration.AutomaticChecklist.Tooltip", "击败后会自动标记条目. 禁用需要用户手动检查条目.\n无论启用或禁用, 你都可以通过右键条目名称来对其进行标记." },
        { "Configs.BossLogConfiguration.BossLogColor.Label", "Boss日志颜色" },
        { "Configs.BossLogConfiguration.BossLogColor.Tooltip", "自定义你的Boss日志的颜色!" },
        { "Configs.BossLogConfiguration.BossLogPos.Label", "打开Boss日志的按钮的位置" },
        { "Configs.BossLogConfiguration.BossLogPos.Tooltip", "在游戏中按住鼠标右键即可轻松将按钮移动到任意位置!\n位置从屏幕右下角开始测量." },
        { "Configs.BossLogConfiguration.CheckDroppedLoot.Label", "只检查可掉落的战利品" },
        { "Configs.BossLogConfiguration.CheckDroppedLoot.Tooltip", "如音乐盒这种不会由条目掉落的物品将不会计入战利品检查." },
        { "Configs.BossLogConfiguration.ColoredBossText.Label", "Boss文本变色" },
        { "Configs.BossLogConfiguration.ColoredBossText.Tooltip", "目录中的Boss文本在被击败时将变为绿色, 在未击败时将变为红色.\n如果启用了'提示下一个要挑战的Boss', 则下个Boss将为黄色." },
        { "Configs.BossLogConfiguration.Debug.Label", "[i:3625] [c/ffeb6e:Mod开发者的Debug工具] [i:3619]" },
        { "Configs.BossLogConfiguration.Debug.Tooltip", "" },
        { "Configs.BossLogConfiguration.DisableProgressionMode.Label", "禁用渐进式日志" },
        { "Configs.BossLogConfiguration.DisableProgressionMode.Tooltip", "" },
        { "Configs.BossLogConfiguration.DisplayName", "自定义Boss日志" },
        { "Configs.BossLogConfiguration.DrawNextMark.Label", "提示下一个要挑战的Boss" },
        { "Configs.BossLogConfiguration.DrawNextMark.Tooltip", "在状态框中作一个标记, 表明它是下一个需要被击败的Boss." },
        { "Configs.BossLogConfiguration.EnableProgressionMode.Label", "启用渐进式日志" },
        { "Configs.BossLogConfiguration.EnableProgressionMode.Tooltip", "" },
        { "Configs.BossLogConfiguration.FilterBosses.Label", "过滤日志中不符合条件的Boss" },
        { "Configs.BossLogConfiguration.FilterBosses.Tooltip", "" },
        { "Configs.BossLogConfiguration.FilterEvents.Label", "过滤日志中不符合条件的事件" },
        { "Configs.BossLogConfiguration.FilterEvents.Tooltip", "" },
        { "Configs.BossLogConfiguration.FilterMiniBosses.Label", "过滤日志中不符合条件的小Boss" },
        { "Configs.BossLogConfiguration.FilterMiniBosses.Tooltip", "" },
        { "Configs.BossLogConfiguration.Headers.BlindMode", "[i:888] [c/ffeb6e:渐进式日志 - 击败Boss以解锁其条目!]" },
        { "Configs.BossLogConfiguration.Headers.BossLogChecklist", "[i:903] [c/ffeb6e:Boss日志清单]" },
        { "Configs.BossLogConfiguration.Headers.BossLogUI", "[i:149] [c/ffeb6e:Boss日志UI]" },
        { "Configs.BossLogConfiguration.HideUnavailable.Label", "隐藏不可用的Boss" },
        { "Configs.BossLogConfiguration.HideUnavailable.Tooltip", "如果启用, 则在Boss日志的目录中移除不可用的Boss.\n例如非圣诞节时的雪人军团." },
        { "Configs.BossLogConfiguration.HideUnsupported.Label", "隐藏没有引用的Boss" },
        { "Configs.BossLogConfiguration.HideUnsupported.Tooltip", "如果启用, 则尚未完美引用的Boss将从Boss日志的目录中隐藏." },
        { "Configs.BossLogConfiguration.LootChecklist.Label", "开启战利品/收藏品清单" },
        { "Configs.BossLogConfiguration.LootChecklist.Tooltip", "目录还会检查你是否获得了Boss的所有战利品和收藏品." },
        { "Configs.BossLogConfiguration.MaskBossLoot.Label", "隐藏Boss掉落物直至其条目被击败" },
        { "Configs.BossLogConfiguration.MaskBossLoot.Tooltip", "" },
        { "Configs.BossLogConfiguration.MaskHardMode.Label", "隐藏困难模式内容直至玩家处于困难模式" },
        { "Configs.BossLogConfiguration.MaskHardMode.Tooltip", "隐藏所有内容, 覆盖上面选择的选项." },
        { "Configs.BossLogConfiguration.MaskNames.Label", "隐藏名称直至其条目被击败" },
        { "Configs.BossLogConfiguration.MaskNames.Tooltip", "" },
        { "Configs.BossLogConfiguration.MaskTextures.Label", "隐藏材质直至其条目被击败" },
        { "Configs.BossLogConfiguration.MaskTextures.Tooltip", "" },
        { "Configs.BossLogConfiguration.OnlyBosses.Label", "在Boss日志中仅显示Boss内容" },
        { "Configs.BossLogConfiguration.OnlyBosses.Tooltip", "如果启用, 则清单和导航页仅会显示访问Boss条目.\n备注: 启用后会忽略下方的过滤设置." },
        { "Configs.BossLogConfiguration.ProgressionPrompt.Label", "禁用渐进式日志提示" },
        { "Configs.BossLogConfiguration.ProgressionPrompt.Tooltip", "如果启用, 则阻止用于新创建的人物的提示出现." },
        { "Configs.BossLogConfiguration.ProgressiveChecklist.Label", "渐进式日志" },
        { "Configs.BossLogConfiguration.ProgressiveChecklist.Tooltip", "隐藏内容, 直至遇见或击败条目." },
        { "Configs.BossLogConfiguration.SelectedCheckmarkType.Label", "清单标记类型" },
        { "Configs.BossLogConfiguration.SelectedCheckmarkType.Tooltip", "" },
        { "Configs.BossLogConfiguration.ShowInteractionTooltips.Label", "启用交互栏" },
        { "Configs.BossLogConfiguration.ShowInteractionTooltips.Tooltip", "启用后, 一个小的标签栏会悬浮在上方, 用以解释如何使用当前页面的可选交互.\n可选交互示例包括右键条目以手动将其标记为已击败." },
        { "Configs.BossLogConfiguration.ShowProgressBars.Label", "显示进度栏" },
        { "Configs.BossLogConfiguration.ShowProgressBars.Tooltip", "禁用后, 目录底部的总进度栏将不会显示." },
        { "Configs.BossLogConfiguration.SpawnItemCraftingChecklist.Label", "启用召唤物制作清单" },
        { "Configs.BossLogConfiguration.SpawnItemCraftingChecklist.Tooltip", "启用后, 生成信息召唤物的制作配方将作为清单.\n背包中有对应数量的材料时, 相应材料需求会自动勾选.\n站在对应的物块的附近时, 相应制作站需求会自动勾选." },
        { "Configs.BossLogConfiguration.UnmaskNextCheck.Label", "显示下一进度条目的名称" },
        { "Configs.BossLogConfiguration.UnmaskNextCheck.Tooltip", "备注: 必须启用'提示下一个要挑战的Boss'和'隐藏Boss名称'后才会生效." },
        { "Configs.CheckType.Check_Empty.Label", "✓  [ ]" },
        { "Configs.CheckType.Check_Empty.Tooltip", "" },
        { "Configs.CheckType.Check_X.Label", "✓  X" },
        { "Configs.CheckType.Check_X.Tooltip", "" },
        { "Configs.CheckType.StrikeThrough.Label", "删除线" },
        { "Configs.CheckType.StrikeThrough.Tooltip", "" },
        { "Configs.CheckType.Tooltip", "" },
        { "Configs.CheckType.X_Empty.Label", "X  [ ]" },
        { "Configs.CheckType.X_Empty.Tooltip", "" },
        { "Configs.Common.HostChange", "仅允许主机更改此配置." },
        { "Configs.Common.InvalidChange", "你不能在{1}存在时更改'{0}'配置!" },
        { "Configs.DebugTools.AccessInternalNames.Label", "访问条目键" },
        { "Configs.DebugTools.AccessInternalNames.Tooltip", "在每个条目页面上添加一个按钮, 其可以显示并将条目键复制到游戏中的剪贴板.\n对于制作跨Mod内容的Mod开发人员很有用." },
        { "Configs.DebugTools.DisableAutoLocalization.Label", "禁用自动本地化" },
        { "Configs.DebugTools.DisableAutoLocalization.Tooltip", "Boss清单会检测旧调用并为新调用所需的LocalizedText提交创建本地化.\n新的调用不需要这些本地化, 但如果传递了null,  则默认使用它们.\n设置为true可防止Boss清单创建新的本地化." },
        { "Configs.DebugTools.EnabledResetOptions.Label", "启用重置数据选项" },
        { "Configs.DebugTools.EnabledResetOptions.Tooltip", "启用后, 你可以清除或重置Boss日志中的某些数据.\n包括: 清除被隐藏的条目、清除被标记的条目、重置战利品清单和重置记录.\n[c/FF0000:此项配置需要启用'启用交互栏'配置后才能启用.]" },
        { "Configs.DebugTools.InactiveBossCheck.Label", "检查不活跃的Boss" },
        { "Configs.DebugTools.InactiveBossCheck.Tooltip", "启用后, 如果启用了记录跟踪, 当记录开始计算时, 聊天框中将显示一条消息.\n如果启用了Boss消失信息, 则当显Boss消失信息时, 这也应该在聊框天中显示一条消息.\n这些信息应该分别在Boss被击败或Boss消失时出现." },
        { "Configs.DebugTools.ModCallLogVerbose.Label", "Mod.Call日志详细信息" },
        { "Configs.DebugTools.ModCallLogVerbose.Tooltip", "如果为true, tModLoader的日志中会显示更多关于创建的条目数据的信息.\n无论设置如何, 都会显示无效或不正确的Mod调用使用" },
        { "Configs.DebugTools.ShowCollectionType.Label", "显示自动检测的集合类型" },
        { "Configs.DebugTools.ShowCollectionType.Tooltip", "Boss的收藏品物品栏会被标记为指定的集合类型" },
        { "Configs.DebugTools.ShowProgressionValue.Label", "使用进度值" },
        { "Configs.DebugTools.ShowProgressionValue.Tooltip", "当光标悬停在目录中的条目上以及查看条目的页面时, 显示其进度值.\n进度值决定了条目在清单中的排序." },
        { "Configs.DebugTools.Tooltip", "" },
        { "Configs.FeatureConfiguration.AllowNewRecords.Label", "允许新记录" },
        { "Configs.FeatureConfiguration.AllowNewRecords.Tooltip", "禁用后, 只会有你以前的尝试会被记录.\n首次胜利和个人的最佳记录不会被覆写." },
        { "Configs.FeatureConfiguration.DespawnMessageType.Label", "Boss消失通告" },
        { "Configs.FeatureConfiguration.DespawnMessageType.Tooltip", "当Boss消失时, 消失信息将出现在聊天栏中.\n如果启用, 请在常规消息或唯一消息之间选择其一." },
        { "Configs.FeatureConfiguration.DisplayName", "其他功能" },
        { "Configs.FeatureConfiguration.DisplayRecordTracking.Label", "显示记录跟踪器数值" },
        { "Configs.FeatureConfiguration.DisplayRecordTracking.Tooltip", "启用后, 记录跟踪数值会在Boss战期间显示并更新.\n备注: 仅适用于单人模式. 在多人模式下不起作用." },
        { "Configs.FeatureConfiguration.EnableBossRadar.Label", "启用Boss雷达" },
        { "Configs.FeatureConfiguration.EnableBossRadar.Tooltip", "" },
        { "Configs.FeatureConfiguration.FragmentsOnMap.Label", "四柱碎片在小地图上显示" },
        { "Configs.FeatureConfiguration.FragmentsOnMap.Tooltip", "" },
        { "Configs.FeatureConfiguration.Headers.BossRadar", "[i:3084] [c/ffeb6e:Boss雷达]" },
        { "Configs.FeatureConfiguration.Headers.BossRecords", "[i:3095] [c/ffeb6e:Boss记录]" },
        { "Configs.FeatureConfiguration.Headers.ChatMessages", "[i:3037] [c/ffeb6e:聊天栏信息]" },
        { "Configs.FeatureConfiguration.Headers.ItemMapDetection", "[i:893] [c/ffeb6e:物品小地图检测]" },
        { "Configs.FeatureConfiguration.LimbMessages.Label", "非Boss的被击败通告" },
        { "Configs.FeatureConfiguration.LimbMessages.Tooltip", "当一位Boss的重要组成部分被击败时会在聊天栏内发送信息.\n如: 骷髅王之手、激光眼/魔焰焰、天界柱，诸如此类." },
        { "Configs.FeatureConfiguration.MoonMessages.Label", "月亮事件结束通告" },
        { "Configs.FeatureConfiguration.MoonMessages.Tooltip", "当原版的月亮事件结束时, 信息将出现在聊天栏中.\n月亮事件包括: 血月、日食、南瓜月和霜月." },
        { "Configs.FeatureConfiguration.NewRecordLogGlow.Label", "启用新记录日志发光" },
        { "Configs.FeatureConfiguration.NewRecordLogGlow.Tooltip", "启用后, 在创造新纪录时下列的内容会发出彩虹光:\n- Boss日志按钮\n- 目录的条目名称" },
        { "Configs.FeatureConfiguration.RadarBlacklist.Label", "雷达黑名单" },
        { "Configs.FeatureConfiguration.RadarBlacklist.Tooltip", "以下被选中的生物将不会被雷达定位." },
        { "Configs.FeatureConfiguration.RadarMiniBosses.Label", "定位小Boss" },
        { "Configs.FeatureConfiguration.RadarMiniBosses.Tooltip", "注意: 此选项仅用于有小地图图像的小Boss." },
        { "Configs.FeatureConfiguration.RadarOpacity.Label", "Boss雷达不透明度" },
        { "Configs.FeatureConfiguration.RadarOpacity.Tooltip", "调整雷达图标的透明度." },
        { "Configs.FeatureConfiguration.RecordTrackingEnabled.Label", "启用Boss记录追踪" },
        { "Configs.FeatureConfiguration.RecordTrackingEnabled.Tooltip", "启用后, 会追踪并生成战斗记录状态" },
        { "Configs.FeatureConfiguration.ScalesOnMap.Label", "暗影鳞片和血腥样本在小地图上显示" },
        { "Configs.FeatureConfiguration.ScalesOnMap.Tooltip", "" },
        { "Configs.FeatureConfiguration.TimeValueFormat.Label", "时间值格式" },
        { "Configs.FeatureConfiguration.TimeValueFormat.Tooltip", "标准格式: [0:00:00.000]\n简化版本: [0h 0m 0s 0ms]" },
        { "Configs.FeatureConfiguration.TimerSounds.Label", "重生倒计时声音" },
        { "Configs.FeatureConfiguration.TimerSounds.Tooltip", "如果启用, 重生时间的最后3秒钟将有声音提示." },
        { "Configs.FeatureConfiguration.TreasureBagsOnMap.Label", "宝藏袋在小地图上显示" },
        { "Configs.FeatureConfiguration.TreasureBagsOnMap.Tooltip", "" },
        { "Configs.FilterType.Hide.Label", "隐藏" },
        { "Configs.FilterType.Hide.Tooltip", "" },
        { "Configs.FilterType.HideWhenCompleted.Label", "完成后隐藏" },
        { "Configs.FilterType.HideWhenCompleted.Tooltip", "" },
        { "Configs.FilterType.Show.Label", "显示" },
        { "Configs.FilterType.Show.Tooltip", "" },
        { "Configs.FilterType.Tooltip", "" },
        { "Configs.MessageType.Disabled.Label", "禁用" },
        { "Configs.MessageType.Disabled.Tooltip", "" },
        { "Configs.MessageType.Generic.Label", "通用" },
        { "Configs.MessageType.Generic.Tooltip", "" },
        { "Configs.MessageType.Tooltip", "" },
        { "Configs.MessageType.Unique.Label", "独特" },
        { "Configs.MessageType.Unique.Tooltip", "" },
        { "Configs.TimeFormat.Simple.Label", "简易" },
        { "Configs.TimeFormat.Simple.Tooltip", "" },
        { "Configs.TimeFormat.Standard.Label", "标准" },
        { "Configs.TimeFormat.Standard.Tooltip", "" },
        { "Configs.TimeFormat.Tooltip", "" },
        { "Keybinds.ToggleChecklist.DisplayName", "开关Boss清单" },
        { "Keybinds.ToggleLog.DisplayName", "开关Boss日志" },
        { "Log.Common.Boss", "Boss" },
        { "Log.Common.BossLog", "Boss日志" },
        { "Log.Common.BossPlural", "Boss" },
        { "Log.Common.Disabled", "禁用" },
        { "Log.Common.Enabled", "启用" },
        { "Log.Common.Entry", "条目" },
        { "Log.Common.Event", "事件" },
        { "Log.Common.EventPlural", "事件" },
        { "Log.Common.MiniBoss", "小boss" },
        { "Log.Common.MiniBossPlural", "小Boss" },
        { "Log.Common.PartiallyEnabled", "部分启用" },
        { "Log.Credits.Devs", "贡献者" },
        { "Log.Credits.Learn", "查看Mod描述以学习" },
        { "Log.Credits.Mods", "已注册的Mod" },
        { "Log.Credits.ModsEmpty", "你已加载的Mod没有注册." },
        { "Log.Credits.NoIcon", "未找到Mod图标!" },
        { "Log.Credits.Notice", "[列表仅包含已加载的Mod]" },
        { "Log.Credits.Register", "注册你自己的Mod!" },
        { "Log.Credits.Titles.CoOwner", "共同所有者 & 维护者" },
        { "Log.Credits.Titles.Contributor", "代码贡献者" },
        { "Log.Credits.Titles.EarlyTesting", "早期测试" },
        { "Log.Credits.Titles.Owner", "创造者 & 所有者" },
        { "Log.Credits.Titles.Sprites", "Boss日志贴图" },
        { "Log.EntryPage.CopyKey", "点击以复制内部'Boss键值'至剪切板\n{0}" },
        { "Log.EntryPage.Defeated", "在{0}{1}中已被击败" },
        { "Log.EntryPage.LogFeaturesNotAvailable", "记录、召唤物和战利品表不可用. 该Mod未提交足够的信息以供使用或引用不正确." },
        { "Log.EntryPage.NotImplemented", "该页面暂不可用. 该Mod未提交相关引用或引用设置不正确." },
        { "Log.EntryPage.Undefeated", "在{0}中未被击败" },
        { "Log.EntryPage.ViewPage", "点击以查看页面" },
        { "Log.HintTexts.ClearAllRecords", "长按Alt并右键此按钮以重置列表的记录值" },
        { "Log.HintTexts.ClearHidden", "长按Alt并右键此按钮以清除所有被隐藏的条目" },
        { "Log.HintTexts.ClearItems", "长按Alt并右键此按钮以将列表中的所有物品标记为未获取" },
        { "Log.HintTexts.ClearMarked", "长按Alt并左键此按钮以清除所有被标记的条目" },
        { "Log.HintTexts.ClearRecord", "长按Alt并右键记录的图标以重置其值" },
        { "Log.HintTexts.HideEntry", "左键条目以将其从列表中隐藏" },
        { "Log.HintTexts.MarkEntry", "右键条目以将其标记为已击败" },
        { "Log.HintTexts.RemoveItem", "长按Alt并右键物品以将选定的物品标记为未获取" },
        { "Log.Indicator.AutomaticChecklist", "清单将自动检查条目" },
        { "Log.Indicator.ManualChecklist", "条目必须由用户手动勾选" },
        { "Log.Indicator.OnlyBossContentDisabled", "能显示所有内容" },
        { "Log.Indicator.OnlyBossContentEnabled", "只能显示Boss内容" },
        { "Log.Indicator.ProgressionMode", "渐进式日志已{0}" },
        { "Log.LootAndCollection.ItemIsExpertOnly", "此物品仅在专家模式下可获得" },
        { "Log.LootAndCollection.ItemIsLocked", "此物品仅在满足特殊需求后解锁" },
        { "Log.LootAndCollection.ItemIsMasterOnly", "此物品仅在大师模式下可获得" },
        { "Log.LootAndCollection.MaskedItems", "击败条目以查看其战利品和收藏品" },
        { "Log.LootAndCollection.Obtained", "已获得此物品!" },
        { "Log.LootAndCollection.Researched", "已研究此物品!" },
        { "Log.ProgressionMode.AskEnable", "你想要开启渐进式日志吗?" },
        { "Log.ProgressionMode.BeforeYouBegin", "在你开始之前..." },
        { "Log.ProgressionMode.Description", "渐进式日志将限制并隐藏许多Boss内容, 直至条目被击败或标记为已完成. 如果你想进行盲打通关, 可以考虑启用此功能. Boss日志将被禁用, 直至你做出选择或在设置中禁用提示后重新打开." },
        { "Log.ProgressionMode.DisablePrompt", "不再显示此内容" },
        { "Log.ProgressionMode.IsEnabled", "[i:888] 渐进式日志已完全或部分启用!\n这会隐藏一些与Boss相关的信息, 直至它们被击败.\n若想禁用或配置渐进式日志, 请前往:\n设置 > Mod设置 > Boss清单: 自定义Boss日志\n并向下滚动至渐进式日志设置" },
        { "Log.ProgressionMode.SelectAnOption", "请在下方选择一项..." },
        { "Log.ProgressionMode.SelectConfig", "关闭Boss日志并配置渐进式日志..." },
        { "Log.ProgressionMode.SelectDisable", "继续并禁用渐进式日志...\n* 解锁所有页面信息内容\n* 没有隐藏. 没有限制." },
        { "Log.ProgressionMode.SelectEnable", "继续并完全启用渐进式日志...\n* 锁定未击败条目的页面信息内容\n* 材质和名称被遮掩\n* Boss战利品被锁定, 直到被击败\n* 启用提示下个挑战, 降低信息局限性 (推荐)" },
        { "Log.Records.Category.Cycle", "全部记录分类" },
        { "Log.Records.Category.FirstVictory", "首次胜利" },
        { "Log.Records.Category.PersonalBest", "个人的最佳记录" },
        { "Log.Records.Category.PreviousAttempt", "上次尝试" },
        { "Log.Records.Category.WorldRecord", "世界纪录" },
        { "Log.Records.ClaimRecord", "成为第一个打破世界纪录的人!" },
        { "Log.Records.Hit", "{0}{^0:受击;受击}" },
        { "Log.Records.Hours", "{0}时{1}分{2}秒({3}毫秒)" },
        { "Log.Records.KDR", "{0}击杀 / {1}死亡" },
        { "Log.Records.Minutes", "{0}分{1}秒({2}毫秒)" },
        { "Log.Records.NewRecord", "新的个人最佳!" },
        { "Log.Records.NewWorldRecord", "新的世界纪录!" },
        { "Log.Records.NoHit", "无伤!" },
        { "Log.Records.NoRecord", "没有记录!" },
        { "Log.Records.PreviousBest", "你以前的最佳纪录" },
        { "Log.Records.RecordHolder", "记录保持者" },
        { "Log.Records.Seconds", "{0}秒{^0:分秒;分秒}({1}毫秒)" },
        { "Log.Records.Title.Duration", "战斗持续时间" },
        { "Log.Records.Title.DurationWorld", "最短时间的战斗" },
        { "Log.Records.Title.FirstVictory", "游戏时间" },
        { "Log.Records.Title.HitsTaken", "受击数" },
        { "Log.Records.Title.HitsTakenWorld", "最低受击次数" },
        { "Log.Records.Title.PersonalBest", "KD比" },
        { "Log.Records.Title.PreviousAttempt", "尝试" },
        { "Log.Records.Title.WorldRecord", "全球击败和死亡次数" },
        { "Log.Records.Tooltip.Duration", "你击败该Boss所用的最短时间!" },
        { "Log.Records.Tooltip.FirstVictory", "首次击败Boss前你的角色处于活动状态的总游戏时间!" },
        { "Log.Records.Tooltip.HitsTaken", "尽可能的闪避攻击! 试着无伤击败该Boss!" },
        { "Log.Records.Tooltip.PersonalBest", "你击败该Boss和该Boss击败你的总次数!" },
        { "Log.Records.Tooltip.PreviousAttempt", "你遭遇该Boss的总次数!" },
        { "Log.Records.Tooltip.WorldRecord", "与该Boss相关的全球击杀和死亡次数!" },
        { "Log.Records.TotalKills", "总击杀" },
        { "Log.Records.Unchallenged", "没有挑战过!" },
        { "Log.SpawnInfo.ByHand", "空手制作" },
        { "Log.SpawnInfo.CycleRecipe", "切换至其他配方" },
        { "Log.SpawnInfo.NoInfo", "无可用信息" },
        { "Log.SpawnInfo.NoSpawnItem", "{0}没有召唤物" },
        { "Log.SpawnInfo.Noncraftable", "此物品无法制作" },
        { "Log.SpawnInfo.RecipeFrom", "配方来自: {0}" },
        { "Log.TableOfContents.AllCollectibles", "已获得所有的收藏品!" },
        { "Log.TableOfContents.AllDropLoot", "已获得所有非收藏品的战利品!" },
        { "Log.TableOfContents.AllLoot", "已获得所有的战利品!" },
        { "Log.TableOfContents.Filter.Disabled", "由于'仅显示Boss内容'设置, 过滤器已禁用" },
        { "Log.TableOfContents.Filter.Hide", "{0}: 隐藏" },
        { "Log.TableOfContents.Filter.HideWhenCompleted", "{0}: 隐藏已击败的" },
        { "Log.TableOfContents.Filter.Show", "{0}: 显示" },
        { "Log.TableOfContents.Filter.ToggleHiddenClose", "确认 & 关闭隐藏列表" },
        { "Log.TableOfContents.Filter.ToggleHiddenOpen", "打开隐藏列表" },
        { "Log.TableOfContents.Hardmode", "困难模式" },
        { "Log.TableOfContents.PreHardmode", "困难模式前" },
        { "Log.TableOfContents.ProgressBarListMods", "点击以切换至Mod列表模式" },
        { "Log.TableOfContents.ProgressBarListTypes", "点击以切换至条目类型模式" },
        { "Log.Tabs.Credits", "感谢页面" },
        { "Log.Tabs.LootAndCollectibles", "战利品 & 收藏品" },
        { "Log.Tabs.NextEntry", "下个{0}:\n{1}" },
        { "Log.Tabs.Records", "挑战记录" },
        { "Log.Tabs.SpawnInfo", "生成信息" },
        { "Log.Tabs.TableOfContents", "目录" },
        { "Log.Tabs.ToggleFilters", "开关过滤器" },
        { "LogMessage.BelongsToInvasion", "{0}已尝试编辑'{1}'的NPC池. 此条目是一个由tModLoader的'NPCID.Sets.BelongsToInvasion'集支持的事件. SubmitEventNPCs仍然受到支持，但建议在给定的情况下使用这些集. 使用这些集用于ModNPCs会自动将它们添加到条目的NPC池中, 而无需额外的mod调用." },
        { "LogMessage.DownedIsNull", "在为[{0}]创建Boss日志条目时提交的参数确定为空. 在ModCall问题解决之前, 条目不会被添加." },
        { "LogMessage.DuplicateEntry", "检查你的代码是否存在重复条目或拼写错误，因为此条目已被注册: [{0}{1}]" },
        { "LogMessage.InvalidEventEntry", "{0}不是事件条目并且无法响应{1}的调用" },
        { "LogMessage.InvalidOrphanKey", "来自{1}的'{0}'调用包含无效键 ({2}) , 将被忽略." },
        { "LogMessage.LastUpdated_ModCall", "BossChecklist ({0})最近更新了Boss日志的Mod调用. 查看GitHub Wiki指南以了解最近的改动!" },
        { "LogMessage.LastUpdated_Progression", "BossChecklist {0}最近更新了原版条目的进度值" },
        { "LogMessage.LateCall", "调用警告: 尝试的消息, '{0}', 过早发送. 预计将不会返回完整的调用信息. 为了获得最佳结果, 请在PostAddRecipes中进行调用." },
        { "LogMessage.ModCallDocumentation", "已更新的BossChecklist的Mod.Call文档在此处: https:" },
        { "LogMessage.MustContainMod", "({0}) 传递的Mod实例无效. 你的调用必须包含Mod实例才能生成条目键." },
        { "LogMessage.MustContainMod_Orphan", "({0}) 传递的Mod实例无效. 为了日志记录，你的调用必须包含Mod实例." },
        { "LogMessage.MustContainName", "({internalName}) 传递的内部名称无效. 你的调用必须包含由字母和/或数字组成的字符串, 并且其中不含空白字符, 以便生成条目键." },
        { "LogMessage.NoLogging", "Boss日志的集成信息将不会被记录." },
        { "LogMessage.OldCall", "调用'{0}'已过时且已被废弃. 请立即使用'{1}'. {2}条目包括: [{3}]" },
        { "LogMessage.OldCall_Orphan", "来自{1}的{0}Mod调用结构不正确. Mod开发者可以参阅以下链接:\nhttps:" },
        { "LogMessage.RegisteredBosses", "{0}已成功注册{1}Boss: {2}" },
        { "LogMessage.RegisteredEvents", "{0}已成功注册{1}事件: {2}" },
        { "LogMessage.RegisteredMiniBosses", "{0}已成功注册{1}小Boss: {2}" },
        { "LogMessage.SuccessfulOrphanData", "{0}已成功注册{1}'{2}'孤立数据值" },
    };

    /// <summary>条目显示名的特例。没列在这里的条目会自动取第一个 NPC 的原版名字。</summary>
    public static readonly Dictionary<string, string> EntryNames = new Dictionary<string, string>
    {
        { "KingSlime", "史莱姆王" },
        { "EyeofCthulhu", "克苏鲁之眼" },
        { "EaterofWorlds", "世界吞噬怪" },
        { "BrainofCthulhu", "克苏鲁之脑" },
        { "QueenBee", "蜂后" },
        { "Skeletron", "骷髅王" },
        { "Deerclops", "独眼巨鹿" },
        { "WallofFlesh", "血肉墙" },
        { "QueenSlimeBoss", "史莱姆皇后" },
        { "TheTwins", "双子魔眼" },
        { "TheDestroyer", "毁灭者" },
        { "SkeletronPrime", "机械骷髅王" },
        { "Plantera", "世纪之花" },
        { "Golem", "石巨人" },
        { "DD2Betsy", "双足飞龙" },
        { "HallowBoss", "光之女皇" },
        { "DukeFishron", "猪龙鱼公爵" },
        { "CultistBoss", "拜月教邪教徒" },
        { "MoonLord", "月亮领主" },
        { "TorchGod", "火把神" },
        { "BloodMoon", "血月" },
        { "GoblinArmy", "哥布林军队" },
        { "OldOnesArmy", "撒旦军队" },
        { "DarkMage", "黑暗魔法师" },
        { "Ogre", "食人魔" },
        { "FrostLegion", "雪人军团" },
        { "PirateInvasion", "海盗入侵" },
        { "PirateShip", "飞翔的荷兰人" },
        { "Eclipse", "日食" },
        { "PumpkinMoon", "南瓜月" },
        { "MourningWood", "哀木" },
        { "Pumpking", "南瓜王" },
        { "FrostMoon", "霜月" },
        { "Everscream", "常绿尖叫怪" },
        { "SantaNK1", "圣诞坦克" },
        { "IceQueen", "冰雪女王" },
        { "MartianMadness", "火星暴乱" },
        { "MartianSaucer", "火星飞碟" },
        { "LunarEvent", "天界柱" },
    };
}
